import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Bangla News",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBengali.className} bg-gray-100 text-gray-900`}
    >
      <link rel="icon" href="/logo.webp" />
      <body className="min-h-full flex flex-col">

        <Header />
        <main>
          {children}
        </main>

        </body>
    </html>
  );
}
